I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\lisan\\Documents\\GitHub\\TheHenhouse\\The Henhouse\\game\\saves\\navigation.json.new' -> 'C:\\Users\\lisan\\Documents\\GitHub\\TheHenhouse\\The Henhouse\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\main.py", line 610, in main
    renpy.dump.dump(False)
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\dump.py", line 262, in dump
    os.rename(new, filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\lisan\\Documents\\GitHub\\TheHenhouse\\The Henhouse\\game\\saves\\navigation.json.new' -> 'C:\\Users\\lisan\\Documents\\GitHub\\TheHenhouse\\The Henhouse\\game\\saves\\navigation.json'

Windows-10-10.0.17763 AMD64
Ren'Py 8.0.1.22070801
The Henhouse 1.0
Fri Nov 25 16:00:20 2022
